### PR TITLE
Remove typescript from dependencies

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by rchl** [comment]
@jfcherng I see you've handled that already. Just not sure about specifying exact version of typescript. Probably not needed.

**Comment by jfcherng** [comment]
> @jfcherng I see you've handled that already. Just not sure about specifying exact version of typescript. Probably not needed.

True. But I have the reason in the source. https://github.com/sublimelsp/LSP-css/blob/3f902dfaf0e7760109d01a5c1c0077f0a25e767f/language-server/compile-language-server.sh#L58-L59

**Comment by jfcherng** [comment]
Or maybe grep that version from the server repo and use it 🤔

**Comment by rchl** [comment]
I suppose leave it at whatever until it breaks. Probably would break on compilation so we would catch it.

**Pull request closed without merging**
